services:
  labeler:
    build: .
    ports:
      - "80:4100"
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DID=${DID}
      - SIGNING_KEY=${SIGNING_KEY}
      - DB=${DB}
    volumes:
      - type: bind
        source: ./labels
        target: /app/labels
        is_directory: true